BEGIN;

TRUNCATE
  users,
  user_info,
  user_genres,
  user_platforms,
  user_matches,
  user_rejections
  RESTART IDENTITY CASCADE;

INSERT INTO users (email, password)
VALUES
  ('user@demo.com', '$2b$12$KRQIdXbRw4QwTxRl.gfZVevKFOnLK7CuM6okwYOFdwghTd2UjNNmW'),
  ('gamerdude22@test.com', '$2a$12$Pkxp8JTF90HG6gYbIKJiiuzPjBHSOcpe1oUY6c1ESHcZ0ISUHmm0K'),
  ('lonelygamer69@test.com', '$2a$12$Pkxp8JTF90HG6gYbIKJiiuzPjBHSOcpe1oUY6c1ESHcZ0ISUHmm0K'),
  ('player63@test.com', '$2a$12$Pkxp8JTF90HG6gYbIKJiiuzPjBHSOcpe1oUY6c1ESHcZ0ISUHmm0K'),
  ('iliketrains@test.com', '$2a$12$Pkxp8JTF90HG6gYbIKJiiuzPjBHSOcpe1oUY6c1ESHcZ0ISUHmm0K'),     
  ('player3@test.com', '$2a$12$Pkxp8JTF90HG6gYbIKJiiuzPjBHSOcpe1oUY6c1ESHcZ0ISUHmm0K'),
  ('yellowbanana@test.com', '$2a$12$Pkxp8JTF90HG6gYbIKJiiuzPjBHSOcpe1oUY6c1ESHcZ0ISUHmm0K'),
  ('yikes@test.com', '$2a$12$Pkxp8JTF90HG6gYbIKJiiuzPjBHSOcpe1oUY6c1ESHcZ0ISUHmm0K'),
  ('idkwhatimdoing@test.com', '$2a$12$Pkxp8JTF90HG6gYbIKJiiuzPjBHSOcpe1oUY6c1ESHcZ0ISUHmm0K'),
  ('gaming4life@test.com', '$2a$12$Pkxp8JTF90HG6gYbIKJiiuzPjBHSOcpe1oUY6c1ESHcZ0ISUHmm0K'),
  ('gamesrfun@test.com', '$2a$12$Pkxp8JTF90HG6gYbIKJiiuzPjBHSOcpe1oUY6c1ESHcZ0ISUHmm0K'),    
  ('player1@test.com', '$2a$12$Pkxp8JTF90HG6gYbIKJiiuzPjBHSOcpe1oUY6c1ESHcZ0ISUHmm0K');

INSERT INTO user_info (display_name, bio, lfm_in, avatar, xbox, psn, nintendo, discord, steam, other, user_id)
VALUES
  ('gamerdude22', 'I like games dude', 'Fortnite,COD Warzone,Overwatch', 'https://katia-app.s3-us-west-1.amazonaws.com/default_avatar.png', 'gamerdude22', null, null, 'gamerdude22#1277', 'gamerdude22', 'BattleNet: gamerdude22#3572', 1),
  ('lonelygamer69', 'I need friends', 'Minecraft,Rust,Ark', 'https://katia-app.s3-us-west-1.amazonaws.com/default_avatar.png', null, 'lonelygamer', null, 'lonelygamer#1872', 'lonelygamer', null, 2),
  ('player63', 'I like playing games', 'COD Warzone,Fortnite,CSGO', 'https://katia-app.s3-us-west-1.amazonaws.com/default_avatar.png', null, null, 'player63', 'player63#9763', 'player63', null, 3),
  ('iliketrains', 'I like trains', 'Fortnite,Apex Legends,COD Warzone', 'https://katia-app.s3-us-west-1.amazonaws.com/default_avatar.png', 'iliketrains', 'iliketrains', null, null, null, null, 4),
  ('player3', 'I like playing games', 'Overwatch,COD Modern Warfare', 'https://katia-app.s3-us-west-1.amazonaws.com/default_avatar.png', null, 'player3', null, 'player3#4578', 'player3', null, 5),
  ('yellowbanana', 'I like bananas', 'COD Modern Warfare,Destiny 2,Overwatch', 'https://katia-app.s3-us-west-1.amazonaws.com/default_avatar.png', 'yellowbanana', 'yellowbanana', null, 'yellowbanana#1277', 'yellowbanana', 'BattleNet: yellowbanana#9874', 6),
  ('yikes', 'oof', 'Destiny 2,Overwatch,Minecraft', 'https://katia-app.s3-us-west-1.amazonaws.com/default_avatar.png', null, 'yikes', null, null, null, 'BattleNet: yikes#8745', 7),
  ('idkwhatimdoing', 'what is going on', 'COD Warzone,Fortnite,Apex Legends', 'https://katia-app.s3-us-west-1.amazonaws.com/default_avatar.png', 'idkwhatimdoing', 'idkwhatimdoing', 'idkwhatimdoing', null, null, null, 8),
  ('gaming4life', 'gaming is life', 'CSGO,COD Modern Warfare', 'https://katia-app.s3-us-west-1.amazonaws.com/default_avatar.png', null, 'gaming4life', null, 'gaming4life#7434', null, 'Epic Games: gaming4life', 9),
  ('gamesrfun', 'games are fun', 'Fortnite,Apex Legends,COD Warzone', 'https://katia-app.s3-us-west-1.amazonaws.com/default_avatar.png', null, null, null, 'gamesrfun#1867', 'gamesrfun', 'Epic Games: gamesrfun', 10),
  ('player1', 'i like playing', 'Minecraft,Conan Exiles,Rust', 'https://katia-app.s3-us-west-1.amazonaws.com/default_avatar.png', 'player1', 'player1', null, null, null, null, 11);

INSERT INTO user_genres (user_id, genre)
VALUES
  (1, 'Battle Royale'),
  (1, 'FPS'),
  (2, 'Battle Royale'),
  (2, 'MMO'),
  (2, 'RPG'),
  (3, 'MOBA'),
  (3, 'FPS'),
  (3, 'MMO'),
  (4, 'Battle Royale'),
  (5, 'Racing'),
  (5, 'Simulation'),
  (6, 'Action'),
  (6, 'Adventure'),
  (6, 'Horror'),
  (7, 'Sports'),
  (7, 'Racing'),
  (7, 'Platformer'),
  (8, 'RPG'),
  (8, 'FPS'),
  (9, 'Horror'),
  (9, 'MMO'),
  (9, 'MOBA'),
  (10, 'FPS'),
  (10, 'VR'),
  (10, 'Puzzle'),
  (11, 'Action'),
  (11, 'Adventure'),
  (11, 'Battle Royale');

INSERT INTO user_platforms (user_id, platform)
VALUES
  (1, 'PlayStation'),
  (1, 'PC'),
  (2, 'PC'),
  (2, 'Xbox'),
  (3, 'Nintendo'),
  (3, 'PC'),
  (4, 'Xbox'),
  (4, 'PlayStation'),
  (5, 'PC'),
  (5, 'PlayStation'),
  (6, 'PC'),
  (6, 'Xbox'),
  (6, 'PlayStation'),
  (7, 'PC'),
  (7, 'PlayStation'),
  (8, 'Xbox'),
  (8, 'PlayStation'),
  (8, 'Nintendo'),
  (9, 'PC'),
  (9, 'Xbox'),
  (10, 'PC'),
  (11, 'PlayStation'),
  (11, 'Xbox');

INSERT INTO user_matches (user_id, match_user_id)
VALUES
  (1, 2),
  (1, 5),
  (1, 3),
  (1, 7),
  (2, 1),
  (2, 5),
  (2, 9),
  (3, 1),
  (3, 10),
  (4, 6), 
  (4, 10),
  (4, 11),
  (4, 2),
  (5, 10),
  (5, 1),
  (5, 3),
  (5, 9),
  (6, 11),
  (6, 5),
  (6, 8),
  (6, 2),
  (6, 4),
  (7, 11),
  (7, 2),
  (7, 11),
  (7, 9),
  (7, 5),
  (8, 10),
  (8, 5),
  (8, 3),
  (9, 10),
  (9, 4),
  (9, 2),
  (9, 4),
  (10, 9),
  (10, 11),
  (10, 5),
  (10, 3),
  (10, 7),
  (11, 10),
  (11, 9),
  (11, 5),
  (11, 2),
  (11, 7),
  (11, 8);
  
COMMIT;
